<?php

declare(strict_types=1);

/**
 * Regenerates the example catalog in the top-level README.md.
 *
 * Scans every `<name>/` directory that has a composer.json + README.md, extracts
 * the FT number (from composer.json description), the pattern title (README H1),
 * a security marker (README mentions ATK/VULN), and the primary howto slug (first
 * docs/howto/<slug>.md link in the README), then rewrites the table between the
 *   <!-- INDEX:START --> ... <!-- INDEX:END -->
 * markers in README.md.
 *
 * Usage:
 *   php tools/build-index.php            # rewrite README.md
 *   php tools/build-index.php --check    # exit 1 if README.md is out of date (CI/drift)
 *
 * No Composer dependencies — runs under a bare php8.4.
 */

const HOWTO_BASE = 'https://github.com/hideyukiMORI/NENE2/blob/main/docs/howto/';

$root = dirname(__DIR__);
$check = in_array('--check', $argv, true);

/** @var list<array{ft:int, name:string, title:string, howto:?string, sec:bool}> $rows */
$rows = [];

$entries = glob($root . '/*', GLOB_ONLYDIR) ?: [];
foreach ($entries as $dir) {
    $name = basename($dir);
    $composerPath = $dir . '/composer.json';
    $readmePath = $dir . '/README.md';
    if (!is_file($composerPath) || !is_file($readmePath)) {
        continue; // not an example directory
    }

    $composer = json_decode((string) file_get_contents($composerPath), true);
    $desc = is_array($composer) && is_string($composer['description'] ?? null) ? $composer['description'] : '';
    $readme = (string) file_get_contents($readmePath);

    // FT number — authoritative source is the composer.json description.
    $ft = 0;
    if (preg_match('/FT(\d+)/', $desc, $m) === 1) {
        $ft = (int) $m[1];
    }

    // Pattern title — README H1, stripped of the "<name> — " and "FTnnn:" prefixes.
    $title = $name;
    if (preg_match('/^#\s+(.+)$/m', $readme, $h) === 1) {
        $title = trim($h[1]);
        if (str_contains($title, '—')) {
            $title = trim(explode('—', $title, 2)[1]);
        }
        $title = preg_replace('/^FT\d+\s*[:：]\s*/u', '', $title) ?? $title;
    }

    // Primary howto slug — first docs/howto/<slug>.md reference in the README.
    $howto = null;
    if (preg_match('#docs/howto/([a-z0-9-]+)\.md#', $readme, $hm) === 1) {
        $howto = $hm[1];
    }

    // Security marker — the example exercises an ATK or VULN assessment.
    $sec = preg_match('/\bATK\b|\bVULN\b|Vulnerability/i', $readme) === 1;

    $rows[] = ['ft' => $ft, 'name' => $name, 'title' => $title, 'howto' => $howto, 'sec' => $sec];
}

usort($rows, static function (array $a, array $b): int {
    return [$a['ft'], $a['name']] <=> [$b['ft'], $b['name']];
});

$secCount = count(array_filter($rows, static fn (array $r): bool => $r['sec']));

$lines = [];
$lines[] = sprintf('_%d examples · %d with ATK/VULN security assessments. Generated by `tools/build-index.php` — do not edit by hand._', count($rows), $secCount);
$lines[] = '';
$lines[] = '| FT | Example | Pattern | Sec | Howto |';
$lines[] = '|----|---------|---------|-----|-------|';
foreach ($rows as $r) {
    $ftCell = $r['ft'] > 0 ? (string) $r['ft'] : '—';
    $exampleCell = sprintf('[%s](./%s/)', $r['name'], $r['name']);
    $secCell = $r['sec'] ? '🛡️' : '';
    $howtoCell = $r['howto'] !== null ? sprintf('[%s](%s%s.md)', $r['howto'], HOWTO_BASE, $r['howto']) : '';
    $lines[] = sprintf('| %s | %s | %s | %s | %s |', $ftCell, $exampleCell, $r['title'], $secCell, $howtoCell);
}
$table = implode("\n", $lines);

$readmePath = $root . '/README.md';
$readme = (string) file_get_contents($readmePath);

$startMarker = '<!-- INDEX:START -->';
$endMarker = '<!-- INDEX:END -->';
$block = $startMarker . "\n" . $table . "\n" . $endMarker;

if (str_contains($readme, $startMarker) && str_contains($readme, $endMarker)) {
    $updated = preg_replace(
        '/' . preg_quote($startMarker, '/') . '.*?' . preg_quote($endMarker, '/') . '/s',
        $block,
        $readme,
    ) ?? $readme;
} else {
    // First run: replace the body of the "## Index" section (up to the next "## ").
    $pattern = '/(##\s+Index\s*\n)(.*?)(\n##\s)/s';
    if (preg_match($pattern, $readme) !== 1) {
        fwrite(STDERR, "Could not find an '## Index' section or INDEX markers in README.md\n");
        exit(1);
    }
    $updated = preg_replace($pattern, "$1\n" . $block . "\n$3", $readme) ?? $readme;
}

if ($check) {
    if ($updated !== $readme) {
        fwrite(STDERR, "README.md index is out of date. Run: php tools/build-index.php\n");
        exit(1);
    }
    echo "Index is up to date ({$secCount} security / " . count($rows) . " examples).\n";
    exit(0);
}

file_put_contents($readmePath, $updated);
echo 'Indexed ' . count($rows) . " examples ({$secCount} with ATK/VULN) into README.md\n";
